version: "3.8"

services:
  db:
    container_name: user_notes_db
    build: ./postgres
    image: ${IMAGE_DB}
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    logging:
      driver: journald
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  app:
    container_name: user_notes_app
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: ${IMAGE_APP}
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: always
    volumes:
      - static_volume:/src/static/
      - media_volume:/src/media/
    logging:
      driver: journald
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    container_name: user_notes_nginx
    build: ./nginx
    image: ${IMAGE_NGINX}
    restart: always
    ports:
      - ${PORT}:80
    depends_on:
      - app
    volumes:
      - static_volume:/src/static/
      - media_volume:/src/media/
      - nginx_log_volume:/var/log/nginx
    logging:
      driver: journald

volumes:
  db_volume:
  static_volume:
  media_volume:
  nginx_log_volume:
